version: '3.8'
services:
  suricata:
    build: .
    container_name: suricata-ids
    network_mode: host  # Necesario para análisis de tráfico
    cap_add:
      - NET_ADMIN
      - SYS_NICE  # Para prioridad de procesos
    volumes:
      - ./suricata.yaml:/etc/suricata/suricata.yaml
      - ./logs:/var/log/suricata
      - ./rules:/var/lib/suricata/rules
    environment:
      - INTERFACE=eth0  # Cambiar según tu interfaz
    restart: unless-stopped
    mem_limit: 256m
    cpus: 0.5
