version: '3.8'
services:
  openvas:
    image: immauss/openvas:latest
    container_name: openvas-lite
    user: "1000:1000"  # Ejecutar como usuario no-root
    restart: unless-stopped
    environment:
      - OV_UPDATE=no
      - SKIP_WAIT=yes
      - MAX_CPUS=1
      - REDIS_MAX_MEMORY=64mb
      - OV_PRELOAD_CACHE=no
    volumes:
      - ./data:/var/lib/openvas
      - ./config:/etc/openvas
    ports:
      - "9390:9390"
    mem_limit: 768m
    mem_reservation: 512m
    cpus: 0.8
    healthcheck:
      test: ["CMD", "curl", "-kf", "https://localhost:9390"]
      interval: 1m
      timeout: 10s
      retries: 10
